import type { Metadata } from "next";
import { Playfair_Display, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { SessionProvider } from "next-auth/react";

import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";

const playfair = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"], // Mendukung karakter Latin
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"], // Mendukung karakter Latin
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfair.variable} ${inter.variable} antialiased`}>
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
        <SessionProvider>
          <Navbar />
          <main className="pt-[3rem]">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
